<?php

return [
    'network-security' => [
        'meta_title' => 'Professional Network & Security Training Program | Megabyte Academy',
        'meta_description' => 'Join Megabyte Academy, a training arm of ADYSURVE LTD, for a practical 6-month Network & Security Training Program covering IT infrastructure, networking, cybersecurity, and career readiness.',
        'title' => 'Professional Network & Security Training Program',
        'subtitle' => 'Build a Career in IT Infrastructure, Networking & Cybersecurity',
        'kicker' => 'Become Industry-Ready with ADYSURVE LTD',
        'service' => 'Professional Network & Security Training Program',
        'duration' => '6 Months',
        'facts' => [
            ['icon' => 'heroicon-o-wrench-screwdriver', 'label' => 'Training Format', 'value' => 'Practical & Hands-on'],
            ['icon' => 'heroicon-o-computer-desktop', 'label' => 'Mode', 'value' => 'Physical / Hybrid / Corporate Sessions'],
            ['icon' => 'heroicon-o-document-check', 'label' => 'Certification', 'value' => 'Certificate of Completion Provided'],
        ],
        'intro' => [
            'Technology powers today&rsquo;s world, and organizations everywhere depend on secure and reliable IT systems to operate efficiently. At ADYSURVE LTD, we are committed to raising the next generation of skilled IT professionals through our comprehensive <strong class="text-white">6-Month Network & Security Training Program</strong> designed for individuals, students, entrepreneurs, IT enthusiasts, and corporate organizations.',
            'Our training combines practical experience, modern industry standards, and real-world IT infrastructure knowledge to equip participants with valuable technical skills that are highly demanded in today&rsquo;s digital economy.',
            'Whether you are starting a career in Information Technology, seeking professional development, or upgrading your organization&rsquo;s workforce, our training program provides the knowledge and hands-on experience needed to succeed in the fast-growing technology industry.',
        ],
        'why' => [
            'label' => 'Why Choose ADYSURVE LTD Training?',
            'heading' => 'Learning that goes beyond theory.',
            'text' => 'At ADYSURVE LTD, we believe learning should go beyond theory. Our training approach focuses on practical implementation, hands-on labs, and real-world scenarios that prepare students for actual IT environments.',
            'items' => ['Hands-on practical sessions', 'Industry-standard training approach', 'Real-world networking scenarios', 'Beginner-friendly learning structure', 'Corporate and individual training options', 'Experienced instructors and IT professionals', 'Career-focused curriculum', 'Continuous mentorship and support', 'Small class sizes for better learning', 'Certificate of completion after training'],
        ],
        'curriculum' => [
            'heading' => 'A 6-month curriculum for networking, IT infrastructure, and cybersecurity.',
            'text' => 'Our 6-month program covers essential and advanced concepts in networking, IT infrastructure, and cybersecurity.',
            'modules' => [
                ['Module 1: Computer & IT Fundamentals', ['Introduction to Information Technology', 'Computer hardware and software basics', 'Operating systems fundamentals', 'Internet and networking basics', 'Troubleshooting computer systems']],
                ['Module 2: Networking Fundamentals', ['Network types and topologies', 'IP addressing and subnetting', 'Routers and switches configuration', 'LAN and WAN setup', 'Wireless networking', 'Structured cabling systems']],
                ['Module 3: IT Infrastructure & Support', ['Server setup and administration', 'System maintenance and upgrades', 'IT support operations', 'Backup and recovery systems', 'Cloud and remote access basics']],
                ['Module 4: Network Security & Cybersecurity', ['Introduction to cybersecurity', 'Firewall configuration', 'Network protection techniques', 'Threat detection and prevention', 'Data security best practices', 'Password and access management', 'Security monitoring fundamentals']],
                ['Module 5: Practical Installation & Configuration', ['Network device installation', 'CCTV and surveillance integration basics', 'Real-world networking projects', 'Office and enterprise network setup', 'Troubleshooting live network issues']],
                ['Module 6: Professional Development & Career Readiness', ['IT career guidance', 'CV and portfolio development', 'Professional communication skills', 'Freelancing and business opportunities in IT', 'Interview preparation and workplace ethics']],
            ],
        ],
        'corporate' => [
            'label' => 'Corporate Training Solutions',
            'heading' => 'Custom IT and cybersecurity training for organizations.',
            'paragraphs' => [
                'ADYSURVE LTD also provides customized corporate IT and cybersecurity training for businesses, schools, organizations, and institutions. Our corporate training programs are designed to improve staff productivity, strengthen cybersecurity awareness, and enhance IT operational efficiency.',
                'We can conduct training:',
            ],
            'methods' => ['On-site at your organization', 'At our training center', 'Hybrid or online sessions'],
            'panel_heading' => 'Corporate Training Areas Include:',
            'items' => ['IT support training', 'Cybersecurity awareness', 'Network management', 'Office IT infrastructure', 'Staff digital skills development', 'Organizational technology support'],
        ],
        'cards' => [
            'apply' => ['heading' => 'Who Can Apply?', 'intro' => 'This training program is suitable for:', 'items' => ['Beginners with no IT background', 'Students and graduates', 'Entrepreneurs and business owners', 'Corporate staff and organizations', 'IT support personnel', 'Professionals seeking career transition', 'Anyone interested in networking and cybersecurity'], 'note' => 'No advanced technical experience is required to get started.'],
            'benefits' => ['heading' => 'Benefits of the Training', 'intro' => 'By the end of the program, participants will:', 'items' => ['Understand modern networking systems', 'Gain practical cybersecurity knowledge', 'Configure and troubleshoot networks', 'Handle basic IT infrastructure support', 'Improve employability and career opportunities', 'Build confidence in handling real IT environments', 'Receive professional training certification']],
            'careers' => ['heading' => 'Career Opportunities After Training', 'intro' => 'Graduates of the program can work as:', 'items' => ['IT Support Technician', 'Network Support Officer', 'System Administrator Assistant', 'Help Desk Personnel', 'CCTV & Security System Technician', 'Junior Network Engineer', 'Technical Support Specialist', 'Freelance IT Consultant']],
        ],
        'cta' => [
            'heading' => 'Join ADYSURVE LTD today.',
            'paragraphs' => [
                'The demand for skilled IT and cybersecurity professionals continues to grow globally. This is the perfect opportunity to gain practical digital skills that can open doors to employment, entrepreneurship, and career advancement.',
                'Join ADYSURVE LTD today and take the first step toward building a successful future in Information Technology, Networking, and Cybersecurity.',
            ],
        ],
    ],
    'cctv-security' => [
        'meta_title' => 'Professional CCTV Installation & Surveillance Security Training | Megabyte Academy',
        'meta_description' => 'Join Megabyte Academy, a training arm of ADYSURVE LTD, for a practical 3-month CCTV Installation & Surveillance Security Training Program.',
        'title' => 'Professional CCTV Installation & Surveillance Security Training',
        'subtitle' => 'Master Modern Security Systems & Build a Career in Surveillance Technology',
        'kicker' => 'Learn Practical CCTV Installation Skills with ADYSURVE LTD',
        'service' => 'Professional CCTV Installation & Surveillance Security Training',
        'duration' => '3 Months',
        'facts' => [
            ['icon' => 'heroicon-o-wrench-screwdriver', 'label' => 'Training Style', 'value' => 'Practical & Hands-on'],
            ['icon' => 'heroicon-o-video-camera', 'label' => 'Mode', 'value' => 'Physical / Hybrid / Corporate Sessions'],
            ['icon' => 'heroicon-o-document-check', 'label' => 'Certification', 'value' => 'Certificate of Completion Included'],
        ],
        'intro' => [
            'Security technology has become an essential part of homes, businesses, schools, banks, hospitals, offices, and public institutions. As the demand for smart surveillance systems continues to increase, skilled CCTV and surveillance professionals are needed more than ever.',
            'At ADYSURVE LTD, we offer a comprehensive <strong class="text-white">3-Month CCTV Installation & Surveillance Security Training Program</strong> designed to equip individuals and corporate organizations with practical knowledge and hands-on experience in modern security system installation, configuration, maintenance, and monitoring.',
            'Our training program combines technical expertise, real-world installation practices, and industry-standard security solutions to prepare participants for successful careers and business opportunities in the security technology industry.',
            'Whether you want to become a professional CCTV installer, improve your technical skills, start your own surveillance business, or train your staff, ADYSURVE LTD provides the right platform to help you succeed.',
        ],
        'why' => [
            'label' => 'Why Choose ADYSURVE LTD Training?',
            'heading' => 'Practical learning for real surveillance projects.',
            'text' => 'At ADYSURVE LTD, we focus on practical learning that prepares participants for real-life surveillance projects and security system management.',
            'items' => ['Practical hands-on installation training', 'Industry-standard security equipment', 'Real-world surveillance project exposure', 'Beginner-friendly teaching approach', 'Experienced instructors and technical experts', 'Corporate and individual training solutions', 'Small class sizes for personalized learning', 'Professional mentorship and support', 'Certificate of completion awarded after training'],
        ],
        'curriculum' => [
            'heading' => 'CCTV installation and surveillance security curriculum.',
            'text' => 'Our training curriculum is carefully designed to cover both basic and advanced CCTV installation and surveillance concepts.',
            'modules' => [
                ['Module 1: Introduction to CCTV & Security Systems', ['Overview of surveillance technology', 'Types of CCTV cameras', 'Analog vs IP camera systems', 'Understanding security system components', 'CCTV industry opportunities']],
                ['Module 2: CCTV Installation Fundamentals', ['Site inspection and security assessment', 'Camera positioning and coverage planning', 'Cable types and cable management', 'Power supply installation', 'Installation safety procedures']],
                ['Module 3: DVR, NVR & System Configuration', ['DVR and NVR setup', 'Camera configuration and integration', 'Hard drive installation and storage management', 'Recording settings and playback', 'Remote viewing setup']],
                ['Module 4: Networking for Surveillance Systems', ['IP addressing for CCTV systems', 'Wireless surveillance systems', 'Router configuration', 'Internet connectivity for remote monitoring', 'Mobile app integration']],
                ['Module 5: Surveillance Security & Monitoring', ['Live monitoring techniques', 'Motion detection setup', 'Security alert systems', 'Access control basics', 'Data protection and surveillance best practices']],
                ['Module 6: Maintenance & Troubleshooting', ['Diagnosing common CCTV faults', 'Camera maintenance', 'Repair and replacement techniques', 'System upgrades and optimization', 'Troubleshooting network and recording issues']],
                ['Module 7: Business & Professional Development', ['Starting a CCTV installation business', 'Customer service and project management', 'Pricing and quotation preparation', 'Professional communication', 'Career opportunities in surveillance technology']],
            ],
        ],
        'corporate' => [
            'label' => 'Corporate Security Training Solutions',
            'heading' => 'Surveillance and security training for organizations.',
            'paragraphs' => ['ADYSURVE LTD also provides professional surveillance and security training for corporate organizations, institutions, schools, hotels, offices, factories, and businesses.'],
            'methods' => ['At your organization', 'At our training center', 'Through customized corporate sessions'],
            'panel_heading' => 'Our corporate training helps organizations:',
            'items' => ['Improve internal security awareness', 'Understand surveillance system operations', 'Train technical personnel', 'Enhance facility monitoring capabilities', 'Reduce security risks and operational vulnerabilities'],
        ],
        'cards' => [
            'apply' => ['heading' => 'Who Can Apply?', 'intro' => 'This program is suitable for:', 'items' => ['Beginners interested in security technology', 'Electricians and technicians', 'IT professionals', 'Students and graduates', 'Entrepreneurs', 'Corporate staff', 'Security personnel', 'Facility managers', 'Anyone interested in CCTV installation and surveillance systems'], 'note' => 'No prior experience is required to enroll.'],
            'benefits' => ['heading' => 'Benefits of the Training', 'intro' => 'After completing the training, participants will:', 'items' => ['Understand modern CCTV systems', 'Install and configure surveillance equipment', 'Set up remote monitoring systems', 'Troubleshoot common surveillance problems', 'Gain practical field experience', 'Build confidence for real installation projects', 'Improve career and business opportunities', 'Receive a professional training certificate']],
            'careers' => ['heading' => 'Career Opportunities After Training', 'intro' => 'Graduates can work as:', 'items' => ['CCTV Installation Technician', 'Surveillance System Specialist', 'Security System Installer', 'Technical Support Personnel', 'Access Control Technician', 'Freelance CCTV Installer', 'Surveillance Maintenance Technician', 'Security Technology Consultant'], 'note' => 'Participants can also start their own CCTV installation and surveillance business.'],
        ],
        'cta' => [
            'heading' => 'Become a certified professional in CCTV Installation & Surveillance Security.',
            'paragraphs' => ['Modern security systems are becoming a necessity in every sector, creating huge demand for trained surveillance professionals. This is your opportunity to gain valuable practical skills in CCTV installation and security technology.', 'Join ADYSURVE LTD today and become a certified professional in CCTV Installation & Surveillance Security.'],
        ],
    ],
    'solar-renewable-energy' => [
        'meta_title' => 'Solar Renewable Energy Design & Installation Training | Megabyte Academy',
        'meta_description' => 'Join Megabyte Academy, a training arm of ADYSURVE LTD, for an intensive 1-month Solar Renewable Energy Design & Installation Training Program.',
        'title' => 'Solar Renewable Energy Design & Installation Training',
        'subtitle' => 'Learn Practical Solar Power Installation Skills in Just 1 Month',
        'kicker' => 'Build a Future in Renewable Energy with ADYSURVE LTD',
        'service' => 'Solar Renewable Energy Design & Installation Training',
        'duration' => '1 Month',
        'facts' => [
            ['icon' => 'heroicon-o-bolt', 'label' => 'Training Style', 'value' => 'Intensive Practical & Hands-on'],
            ['icon' => 'heroicon-o-sun', 'label' => 'Mode', 'value' => 'Physical / Hybrid / Corporate Sessions'],
            ['icon' => 'heroicon-o-document-check', 'label' => 'Certification', 'value' => 'Certificate of Completion Included'],
        ],
        'intro' => [
            'The world is rapidly shifting toward clean, sustainable, and cost-effective energy solutions, and solar power has become one of the fastest-growing industries globally. As homes, businesses, schools, and organizations continue to seek reliable alternatives to unstable electricity supply and rising energy costs, the demand for skilled solar energy professionals continues to increase.',
            'At ADYSURVE LTD, we offer an intensive <strong class="text-white">1-Month Solar Renewable Energy Design & Installation Training Program</strong> designed to equip individuals, technicians, entrepreneurs, and corporate organizations with practical knowledge and hands-on skills in modern solar energy systems.',
            'Our training focuses on real-world solar installation practices, renewable energy fundamentals, system design, maintenance, and troubleshooting to prepare participants for immediate opportunities in the growing renewable energy industry.',
            'Whether you want to become a professional solar installer, start a renewable energy business, upgrade your technical skills, or train your staff, ADYSURVE LTD provides the practical experience and professional guidance you need.',
        ],
        'why' => [
            'label' => 'Why Choose ADYSURVE LTD Solar Training?',
            'heading' => 'Practical solar learning with real equipment.',
            'text' => 'At ADYSURVE LTD, we believe practical learning is the key to professional success. Our training program is designed to help participants understand solar systems from installation to maintenance using real equipment and practical field experience.',
            'items' => ['Hands-on practical training', 'Real solar installation experience', 'Beginner-friendly learning structure', 'Industry-standard equipment and tools', 'Experienced renewable energy instructors', 'Practical troubleshooting sessions', 'Small class sizes for better engagement', 'Professional mentorship and guidance', 'Certificate of completion after training'],
        ],
        'curriculum' => [
            'heading' => 'Solar renewable energy design and installation curriculum.',
            'text' => 'Our intensive 1-month training program covers the essential areas of solar renewable energy design and installation.',
            'modules' => [
                ['Module 1: Introduction to Solar Renewable Energy', ['Basics of renewable energy', 'Understanding solar energy systems', 'Types of solar power systems', 'Components of a solar system', 'Opportunities in the solar energy industry']],
                ['Module 2: Solar Panel & System Design', ['Solar panel sizing and selection', 'Load assessment and energy calculation', 'Battery sizing and configuration', 'Inverter selection and installation', 'Designing efficient solar systems']],
                ['Module 3: Practical Solar Installation', ['Solar panel mounting techniques', 'Electrical wiring and connections', 'Inverter and battery installation', 'Charge controller setup', 'Safety procedures during installation']],
                ['Module 4: System Testing & Maintenance', ['Solar system testing procedures', 'Performance monitoring', 'Fault detection and troubleshooting', 'Battery maintenance', 'Preventive maintenance practices']],
                ['Module 5: Solar Business & Professional Development', ['Starting a solar installation business', 'Customer consultation and project planning', 'Quotation and pricing preparation', 'Professional ethics and customer service', 'Career opportunities in renewable energy']],
            ],
        ],
        'corporate' => [
            'label' => 'Corporate Renewable Energy Training',
            'heading' => 'Customized solar and renewable energy training.',
            'paragraphs' => ['ADYSURVE LTD also provides customized solar and renewable energy training for businesses and organizations, schools and institutions, technical teams, facility management staff, and engineering departments.', 'Our corporate training helps organizations understand solar power implementation, energy efficiency, and sustainable power solutions for improved operational performance.'],
            'methods' => ['At your organization', 'At our training center', 'Through customized practical workshops'],
            'panel_heading' => 'Corporate training is ideal for:',
            'items' => ['Businesses and organizations', 'Schools and institutions', 'Technical teams', 'Facility management staff', 'Engineering departments'],
        ],
        'cards' => [
            'apply' => ['heading' => 'Who Can Apply?', 'intro' => 'This program is suitable for:', 'items' => ['Beginners interested in renewable energy', 'Electricians and technicians', 'Entrepreneurs and business owners', 'Engineering students', 'Graduates and job seekers', 'Corporate staff', 'Facility managers', 'Anyone interested in solar power systems'], 'note' => 'No advanced technical background is required.'],
            'benefits' => ['heading' => 'Benefits of the Training', 'intro' => 'After completing the program, participants will:', 'items' => ['Understand how solar power systems work', 'Design and install solar energy systems', 'Troubleshoot common solar system issues', 'Gain practical installation experience', 'Improve career and business opportunities', 'Build confidence in handling renewable energy projects', 'Receive professional certification']],
            'careers' => ['heading' => 'Career Opportunities After Training', 'intro' => 'Graduates can work as:', 'items' => ['Solar Installation Technician', 'Renewable Energy Technician', 'Solar Maintenance Specialist', 'Solar System Designer', 'Energy Solutions Consultant', 'Technical Support Personnel', 'Freelance Solar Installer'], 'note' => 'Participants can also establish their own solar installation and renewable energy business.'],
        ],
        'cta' => [
            'heading' => 'Become professionally trained in Solar Renewable Energy Design & Installation.',
            'paragraphs' => ['Renewable energy is shaping the future of power generation and energy management. This is your opportunity to gain practical, high-demand skills in one of the world&rsquo;s fastest-growing industries.', 'Join ADYSURVE LTD today and become professionally trained in Solar Renewable Energy Design & Installation.'],
        ],
    ],
    'it-essentials' => [
        'meta_title' => 'IT Essentials for Beginners Training Program | Megabyte Academy',
        'meta_description' => 'Join Megabyte Academy, a training arm of ADYSURVE LTD, for a practical 3-month IT Essentials for Beginners Training Program.',
        'title' => 'IT Essentials for Beginners Training Program',
        'subtitle' => 'Start Your Journey into the World of Information Technology',
        'kicker' => 'Gain Practical Digital Skills with ADYSURVE LTD',
        'service' => 'IT Essentials for Beginners Training Program',
        'duration' => '3 Months',
        'facts' => [
            ['icon' => 'heroicon-o-computer-desktop', 'label' => 'Training Style', 'value' => 'Practical & Hands-on'],
            ['icon' => 'heroicon-o-wifi', 'label' => 'Mode', 'value' => 'Physical / Hybrid / Corporate Sessions'],
            ['icon' => 'heroicon-o-document-check', 'label' => 'Certification', 'value' => 'Certificate of Completion Included'],
        ],
        'intro' => [
            'Technology has become an essential part of everyday life and modern business operations. From communication and education to business management and digital services, computer knowledge and IT skills are now among the most valuable skills in today&rsquo;s world.',
            'At ADYSURVE LTD, we offer a comprehensive <strong class="text-white">3-Month IT Essentials for Beginners Training Program</strong> designed to help students, job seekers, entrepreneurs, office workers, and beginners build a strong foundation in Information Technology.',
            'This training program is beginner-friendly and focuses on practical learning, helping participants develop the confidence and technical skills needed to use computers effectively, understand digital systems, and prepare for advanced technology careers.',
            'Whether you are completely new to computers or looking to improve your digital knowledge, our IT Essentials program provides the right starting point for success in today&rsquo;s digital economy.',
        ],
        'why' => [
            'label' => 'Why Choose ADYSURVE LTD IT Training?',
            'heading' => 'Simple, practical, and accessible technology education.',
            'text' => 'At ADYSURVE LTD, we believe technology education should be simple, practical, and accessible to everyone. Our training is structured to make learning easy while providing hands-on experience with real computer systems and modern digital tools.',
            'items' => ['Beginner-friendly learning environment', 'Hands-on practical computer sessions', 'Step-by-step teaching approach', 'Experienced IT instructors', 'Small class sizes for personalized attention', 'Real-world digital skills training', 'Practical assignments and projects', 'Career-focused learning structure', 'Certificate of completion awarded after training'],
        ],
        'curriculum' => [
            'heading' => 'Core digital and computer skills every beginner should know.',
            'text' => 'Our 3-month IT Essentials training covers the core digital and computer skills every beginner should know.',
            'modules' => [
                ['Module 1: Introduction to Computers', ['Understanding computer systems', 'Types of computers and devices', 'Computer hardware and software basics', 'Input and output devices', 'Computer operating systems']],
                ['Module 2: Basic Computer Operations', ['Using Windows operating system', 'File and folder management', 'Installing and uninstalling software', 'Keyboard shortcuts and productivity tips', 'Computer maintenance basics']],
                ['Module 3: Internet & Digital Literacy', ['Understanding the internet', 'Web browsing and online research', 'Email creation and management', 'Online safety and cybersecurity awareness', 'Digital communication tools']],
                ['Module 4: Microsoft Office & Productivity Tools', ['Microsoft Word for document creation', 'Microsoft Excel basics', 'Microsoft PowerPoint presentations', 'Formatting and professional documentation', 'Office productivity techniques']],
                ['Module 5: Introduction to Networking & IT Support', ['Basic networking concepts', 'Understanding internet connectivity', 'Troubleshooting common computer problems', 'Basic IT support skills', 'Introduction to computer security']],
                ['Module 6: Digital Skills for Career & Business', ['Online collaboration tools', 'Digital workplace skills', 'CV and professional document preparation', 'Freelancing and online opportunities', 'Career guidance in Information Technology']],
            ],
        ],
        'corporate' => [
            'label' => 'Corporate Digital Skills Training',
            'heading' => 'Customized IT Essentials training for teams.',
            'paragraphs' => ['ADYSURVE LTD also offers customized IT Essentials training for businesses and corporate organizations, schools and educational institutions, government agencies, churches and NGOs, and staff and administrative teams.', 'Our corporate IT training helps organizations improve digital literacy, workplace productivity, and technology adoption among staff members.'],
            'methods' => ['At your organization', 'At our training center', 'Through customized group sessions'],
            'panel_heading' => 'Corporate training is ideal for:',
            'items' => ['Businesses and corporate organizations', 'Schools and educational institutions', 'Government agencies', 'Churches and NGOs', 'Staff and administrative teams'],
        ],
        'cards' => [
            'apply' => ['heading' => 'Who Can Apply?', 'intro' => 'This program is suitable for:', 'items' => ['Absolute beginners', 'Students and graduates', 'Job seekers', 'Business owners and entrepreneurs', 'Office workers', 'Teachers and administrators', 'Senior citizens interested in digital literacy', 'Anyone looking to improve computer knowledge'], 'note' => 'No previous computer experience is required.'],
            'benefits' => ['heading' => 'Benefits of the Training', 'intro' => 'After completing the program, participants will:', 'items' => ['Understand how computers and digital systems work', 'Use Microsoft Office tools effectively', 'Browse the internet safely and confidently', 'Handle basic computer troubleshooting', 'Improve productivity and workplace skills', 'Build confidence in using technology', 'Prepare for advanced IT training opportunities', 'Receive a professional certificate of completion']],
            'careers' => ['heading' => 'Career & Learning Opportunities After Training', 'intro' => 'Graduates can progress into:', 'items' => ['IT Support roles', 'Administrative and office positions', 'Data entry and digital operations', 'Customer support services', 'Advanced networking and cybersecurity training', 'Graphic design and digital marketing', 'Freelancing and online work opportunities'], 'note' => 'This training also serves as a foundation for more advanced IT and technology programs.'],
        ],
        'cta' => [
            'heading' => 'Begin your journey into Information Technology.',
            'paragraphs' => ['Digital skills are no longer optional in today&rsquo;s world. This is your opportunity to gain practical computer knowledge and build confidence in using modern technology for work, business, education, and everyday life.', 'Join ADYSURVE LTD today and begin your journey into Information Technology with our IT Essentials for Beginners Training Program.'],
        ],
    ],
    'graphic-design-media' => [
        'meta_title' => 'Graphic Design & Media Communication Training Program | Megabyte Academy',
        'meta_description' => 'Join Megabyte Academy, a training arm of ADYSURVE LTD, for a practical 3-month Graphic Design & Media Communication Training Program.',
        'title' => 'Graphic Design & Media Communication Training Program',
        'subtitle' => 'Learn Creative Design Skills & Build a Career in Digital Media',
        'kicker' => 'Become a Professional Creative Designer with ADYSURVE LTD',
        'service' => 'Graphic Design & Media Communication Training Program',
        'duration' => '3 Months',
        'facts' => [
            ['icon' => 'heroicon-o-paint-brush', 'label' => 'Training Style', 'value' => 'Practical & Hands-on'],
            ['icon' => 'heroicon-o-photo', 'label' => 'Mode', 'value' => 'Physical / Hybrid / Corporate Sessions'],
            ['icon' => 'heroicon-o-document-check', 'label' => 'Certification', 'value' => 'Certificate of Completion Included'],
        ],
        'intro' => [
            'In today&rsquo;s digital world, visual communication plays a major role in business growth, branding, marketing, advertising, and online engagement. Organizations, businesses, churches, schools, and brands constantly need skilled graphic designers and media professionals who can create compelling visual content that captures attention and communicates effectively.',
            'At ADYSURVE LTD, we offer a comprehensive <strong class="text-white">3-Month Graphic Design & Media Communication Training Program</strong> designed to equip beginners, students, entrepreneurs, content creators, and professionals with practical creative design skills and digital media knowledge.',
            'Our training combines creativity, branding, communication strategy, and hands-on practical sessions to prepare participants for real-world opportunities in the creative and digital media industry.',
            'Whether you want to become a professional graphic designer, grow your business brand, work in media communication, create social media content, or start a freelance design career, ADYSURVE LTD provides the right platform to help you succeed.',
        ],
        'why' => [
            'label' => 'Why Choose ADYSURVE LTD Creative Training?',
            'heading' => 'Practical, industry-relevant creative skills.',
            'text' => 'At ADYSURVE LTD, we focus on practical learning and industry-relevant skills that help participants become confident and creative professionals.',
            'items' => ['Hands-on practical design sessions', 'Beginner-friendly learning approach', 'Real-world branding and media projects', 'Industry-standard creative tools', 'Experienced creative instructors', 'Small class sizes for personalized learning', 'Portfolio-building projects', 'Professional mentorship and guidance', 'Certificate of completion after training'],
        ],
        'curriculum' => [
            'heading' => 'Creative and digital communication skills for today&rsquo;s media-driven world.',
            'text' => 'Our 3-month Graphic Design & Media Communication program covers essential creative and digital communication skills needed in today&rsquo;s media-driven world.',
            'modules' => [
                ['Module 1: Introduction to Graphic Design', ['Principles of graphic design', 'Understanding visual communication', 'Color theory and typography', 'Design layout and composition', 'Branding fundamentals']],
                ['Module 2: Graphic Design Software Training', ['Introduction to professional design tools', 'Creating flyers, posters, and banners', 'Logo design techniques', 'Social media graphic creation', 'Image editing and enhancement']],
                ['Module 3: Branding & Media Communication', ['Brand identity development', 'Visual storytelling', 'Advertising and promotional design', 'Corporate communication materials', 'Designing for digital marketing']],
                ['Module 4: Social Media & Content Design', ['Designing content for Facebook, Instagram, TikTok, and YouTube', 'Social media branding strategies', 'Creating engaging digital content', 'Content planning and presentation', 'Media communication techniques']],
                ['Module 5: Practical Creative Projects', ['Real-world design assignments', 'Business branding projects', 'Portfolio development', 'Presentation and client communication', 'Creative workflow management']],
                ['Module 6: Freelancing & Career Development', ['Starting a graphic design business', 'Freelancing opportunities', 'Client management and pricing', 'Building a professional portfolio', 'Career opportunities in creative media']],
            ],
        ],
        'corporate' => [
            'label' => 'Corporate Creative & Media Training',
            'heading' => 'Customized creative training for teams and organizations.',
            'paragraphs' => ['ADYSURVE LTD also offers customized graphic design and media communication training for businesses and corporate organizations, schools and educational institutions, churches and NGOs, marketing and media teams, and entrepreneurs and startups.', 'Our corporate training helps organizations improve branding, communication, digital marketing, and internal media content development.'],
            'methods' => ['At your organization', 'At our training center', 'Through customized workshops and group sessions'],
            'panel_heading' => 'Corporate training is ideal for:',
            'items' => ['Businesses and corporate organizations', 'Schools and educational institutions', 'Churches and NGOs', 'Marketing and media teams', 'Entrepreneurs and startups'],
        ],
        'cards' => [
            'apply' => ['heading' => 'Who Can Apply?', 'intro' => 'This training is suitable for:', 'items' => ['Beginners with no design experience', 'Students and graduates', 'Entrepreneurs and business owners', 'Social media managers', 'Content creators and influencers', 'Church media teams', 'Marketing professionals', 'Anyone interested in graphic design and media communication'], 'note' => 'No prior design experience is required.'],
            'benefits' => ['heading' => 'Benefits of the Training', 'intro' => 'After completing the program, participants will:', 'items' => ['Understand the fundamentals of graphic design', 'Create professional visual content', 'Develop branding and communication materials', 'Design content for social media and marketing', 'Build a professional creative portfolio', 'Improve career and freelance opportunities', 'Gain confidence in visual communication', 'Receive a professional certificate of completion']],
            'careers' => ['heading' => 'Career Opportunities After Training', 'intro' => 'Graduates can work as:', 'items' => ['Graphic Designer', 'Social Media Content Designer', 'Brand Identity Designer', 'Media Communication Assistant', 'Creative Content Creator', 'Digital Marketing Designer', 'Freelance Graphic Designer', 'Visual Communication Specialist'], 'note' => 'Participants can also establish their own creative design and branding business.'],
        ],
        'cta' => [
            'heading' => 'Unlock your creative potential.',
            'paragraphs' => ['Creative design and digital communication skills are among the most in-demand skills in today&rsquo;s digital economy. This is your opportunity to gain practical creative experience and build a successful future in graphic design and media communication.', 'Join ADYSURVE LTD today and unlock your creative potential with our Graphic Design & Media Communication Training Program.'],
        ],
    ],
];
